---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/rempaf5c/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
